#!/bin/bash
# 
# xmonad "startup hook" script. This gets run after xmonad is initialized,
# via the startupHook facility provided by xmonad. It's useful for 
# running any programs which you want to use within xmonad but
# which don't need to be initialized before xmonad is running. 
#
# Author: David Brewer
# Repository: https://github.com/davidbrewer/xmonad-ubuntu-conf

#
# TRAY ICON SOFTWARE
#

# Trayer
#if [ -z "$(pgrep trayer)" ] ; then
#    trayer --edge top --align center --heighttype pixel --height 12 --SetDockType true --widthtype percent --width 10 &
#fi

# Sound Applet
#if [ -z "$(pgrep gnome-sound-applet)" ] ; then
#    gnome-sound-applet &
#fi


# Empathy chat client (-h: start hidden, -n: don't connect on launch)
#if [ -z "$(pgrep empathy)" ] ; then
#    empathy -n &
#fi

# Remmina remote desktop connection client (-i: start hidden)
#if [ -z "$(pgrep remmina)" ] ; then
#    remmina -i &
#fi

# Network manager, so we don't have to configure wifi at the command line.
#if [ -z "$(pgrep nm-applet)" ] ; then
#    nm-applet --sm-disable &
#fi

# Applet for managing print jobs from the tray.
#if [ -z "$(pgrep system-config-printer-applet)" ] ; then
#    system-config-printer-applet &
#fi

#
# APPLICATION LAUNCHER
#

# Use synapse as our app launcher. (-s: don't display until requested) 
#if [ -z "$(pgrep synapse)" ] ; then
#    synapse -s &
#fi


# Chromium
#if [ -z "$(pgrep chromium-browser)" ] ; then
#    chromium-browser &
#fi

# Firefox
if [ -z "$(pgrep firefox)" ] ; then
    firefox &
fi

# gnome-terminal
#if [ -z "$(pgrep gnome-terminal)" ] ; then
#    gnome-terminal &
#    gnome-terminal &
#    gnome-terminal -e "tty-clock -bcC4 -f '%d.%m.%Y'" &
#    gnome-terminal -e "alsamixer" &
#    gnome-terminal -e "irssi" &
#fi

# urxvt + tmux
if [ -z "$(pgrep urxvt)" ] ; then
  tmux ls > /dev/null
  if [ "$?" == "0" ] ; then
    urxvt -e tmux attach -t 0 &
  else
    urxvt -e tmux &
  fi
fi


# nautilus
if [ -z "$(pgrep nauilus)" ] ; then
    nautilus --no-desktop &
fi

# xscreensaver
if [ -z "$(pgrep xscreensaver)" ] ; then
    xscreensaver -nosplash &
fi

# Set Background Image
feh --bg-scale /home/fabian/Bilder/butterfly.jpg &

# On login, we unlock the ssh keychain so we're not prompted for 
# passphrases later. We pipe /dev/null to ssh-add to make it realize 
# it's not running in a terminal. Otherwise, it won't launch the prompt.
# 
# If you don't use the ssh keychain you may not want this. Commented
# by default as it is assumed many users will not want this feature.

# export SSH_ASKPASS="/usr/bin/ssh-askpass"
# cat /dev/null | ssh-add &

# I disable the middle mouse button because otherwise I constantly 
# accidentally paste unwanted text in the middle of my code while scrolling. 
# Note that the id of the mouse device may be different depending on 
# which usb port it is plugged into! To find it, use:
# xinput list |grep 'id='
# In the following command, the id is the first argument, the rest is 
# the remapping.

# Commented by default as it is assumed many users will not want this.
# xinput set-button-map 10 1 0 3 4 5 6 7
